### ISSUE TITLE
Installer should extract node_modules and envs 

### ISSUE THREAD

**Issue by finlay** [stencila/nixta#45]
This makes it easier to install somewhere else in the PATH.

**Comment by nokome** [comment]
@finlay Could you review the new install script https://github.com/stencila/nixster/blob/6c4fcee2b124077f78093d7c0bff022d65bab41b/install.sh#L33-L40 and README instructions https://github.com/stencila/nixster/blob/master/README.md#install.

The current approach is to install into a versioned directory to avoid clashes in `node_modules` in particular between versions and/or other software.
