### ISSUE TITLE
Open to contributers? 😊

### ISSUE THREAD

**Issue by freddie-freeloader** [stencila/nixta#52]
Hey there! :wave: 

I have to admit -- I love this idea! :heart_eyes: 

Nix is a super cool tool, but -- yes indeed -- the UX is not very accessible for most human beings. Plus, there is definitely a case to be made for DSTs (domain specific tools, akin to DSLs). 

Is this repository meant for rapid prototyping, or is there an interest to develop this further and create a comprehensible **and** comprehensive CLI for everyday usage? :blush: 

Best from Berlin,
Jonas :dove:

**Comment by nokome** [comment]
Hi Jonas!

Thanks for the positive feedback. Glad there is someone else that likes the idea!

Yes, we're very keen on contributors, and yes we would like to develop this further as a tool for everyday usage! Right now we are focusing our time on some of the other tools in our stack (e.g. https://github.com/stencila/encoda) but plan to come back to Nixta in 2-3 months.

In the meantime, @finlay has been kicking the tyres a little trying Nixta out on a Haskell based data science project. That may be a good way for you to get a feel for what is missing and what needs to be done.

Or, let me know if you'd like me to make some suggestions on where to start.
